### ISSUE TITLE
Reading NMNIST Dataset

### ISSUE THREAD

**Issue by tehreemnaqvi** [tihbe/python-ebdataset#1]
Hi,

I am trying to read the **NMNIST** Dataset by using your code.

I have files like **"00001.bin"**, in short, **binary format**.

**I have got this error**:

![image](https://user-images.githubusercontent.com/38427571/104692996-41eb4200-574c-11eb-9d84-5336cfc164f2.png)

I don't know how to solve this error?

Can you please help me out what's the problem?

Thanks

**Comment by tihbe** [comment]
Hi,

The DVS datasets return an object of type DVSSpikeTrain, which is more or less a numpy record array with sparse representation, so it won't work out of the box with PyTorch's DataLoader. The DataLoader will try to batch together these DVSSpikeTrain, thus your error.

If you want to use a DataLoader, you have to convert them to tensors using one of the available transforms. For example:

```
from ebdataset.vision.transforms import ToDense
from quantities import ms
dt = 1*ms
NMnist(path, transform=ToDense(dt))
```
This will convert the DVSSpikeTrain into a dense tensor with dt=1ms, and the DataLoader will be able to batch them with the default collate function.

**Comment by tehreemnaqvi** [comment]
I got it.

Thank you very much.
