### ISSUE TITLE
Possible bug with ibm gesture

### ISSUE THREAD

**Issue by Snow-Crash** [tihbe/python-ebdataset#2]
Here is minimal working example:

```
from ebdataset.vision import IBMGesture, H5IBMGesture
from ebdataset.vision.transforms import ToDense
from quantities import ms
H5IBMGesture.convert(DVS_GESTURE_TAR, H5_FILE)
data = H5IBMGesture(H5_FILE)
spike_train = data[0][0]
convert = ToDense(10*ms)
dense = convert(spike_train)
```

Error message:
```
index 26880 is out of bounds for dimension 0 with size 128
  File "/home/myhomefolder/pytorch_env/lib/python3.6/site-packages/ebdataset/vision/transforms.py", line 72, in __call__
    ] = 1
```

I found that the error is because of x and y in dvs spike train, please see below:
```
spike_train.x
array([   49,    82,  7169, ...,     0,     0, 21248], dtype=uint16)
spike_train.x.max()
65531
```
dvs gesture size is 128x128, however, I can find values that are greater than 128 in both spike_train.x and spike_train.y

My environment:
torch==1.2.0
numpy==1.17.4
torchvision==0.4.0
h5py==3.1.0
quantities==0.12.4

**Comment by Snow-Crash** [comment]
I post my solution here. It is caused by numpy version. Becuase I don't want to break my environment, I didn't install depenences specified in setup.py. After upgrading numpy, it is fixed. 
pytorch, h5py and tdqm version seems do not matter.

**Comment by Snow-Crash** [comment]
Additional comment:
h5py version matters. For unclear reason, older version of h5py cannot write correctly. In ebdataset/vision/ibm_gesture.py, following code will not work as expected:

pos[i, 0] = spike_train.x
pos[i, 1] = spike_train.y
pos[i, 2] = spike_train.p

after assign spike_train.x to pos[i, 0], actually value of pos[i, 0] does not equal to spike_train.x. It looks like random number caused by overflow or incorrect read/write offset.

**Comment by tihbe** [comment]
Interesting, thank you for letting me know. @Snow-Crash do you have the number of the non-working h5py version you tried ? I could upgrade the requirements.txt file, if needed, to reflect the minimum required version
